### ISSUE TITLE
Test email not working?

### ISSUE THREAD

**Issue by ryancramerdesign** [teppokoivula/WireMailSwiftMailer#1]
I think the new test email feature might not be working, at least I can't get it to work. Whenever I try it out, I get "A test message was just sent to 0 recipients" regardless of whether I enter one email address or multiple (comma separated).

**Comment by teppokoivula** [comment]
Just checking, but can you confirm that the recipients actually got messages? Which "Transport" were you using?

**Comment by ryancramerdesign** [comment]
The recipient (me) didn't get the messages. This is using the copy
installed at processwire.com, using localhost SMTP. Just upgraded to the
latest WireMailSwiftMailer today. I can set you up as superuser there (if
you aren't already) if you want to have a look?

**Comment by ryancramerdesign** [comment]
Just testing now from modules.processwire.com, I'm not seeing the same issue. Perhaps I'm doing something wrong. I'll do more testing to see if I can track it down.

**Comment by teppokoivula** [comment]
Sorry if this is too obvious, but: this message is supposed to explain how many messages were successfully sent, so if no messages were sent, "0 recipients" sounds just about right.

To be honest the test feature itself is very simple, so it seems unlikely for it specifically to be broken. If recipients are not getting messages at all, it could be a sign of something else being wrong (messages not getting sent, in which case the test feature is working correctly, though the message might be a bit confusing).

Let me know what you find -- I will take another look at this too, but so far I haven't been able to reproduce the issue. Found unrelated minor issue with test tool, but that's it so far. One thing I'm definitely going to do is making the messages from test tool more sensible :)

**Comment by teppokoivula** [comment]
Closing old issues. This one seemed unreproducible.
