### ISSUE TITLE
Password gets cleared on save

### ISSUE THREAD

**Issue by jlahijani** [teppokoivula/WireMailSwiftMailer#2]
Let's say your settings for the module are totally configured.  Then one day you go back to the settings to make a change and hit save, IT WILL WIPE OUT YOUR PASSWORD!!! (sorry, I had a crazy day today).

Tested on PW 3.0.116

**Comment by jlahijani** [comment]
Line 149 needs to be changed from:
```
if (isset($data['SMTPPassword2'])) {
```

To:
```
if (isset($data['SMTPPassword2']) && !empty($data['SMTPPassword2'])) {
```

**Comment by jlahijani** [comment]
Note I'm using PHP 7.2, if that makes a difference.

**Comment by teppokoivula** [comment]
Thanks @jlahijani, and sorry – I'll make sure that this gets fixed later today :)
